### PR TITLE
chore(global): added code linting & security checks

### LINKED ISSUE #9: Ticket N°-1::2: Setup automatic tests

### PR DESCRIPTION
**Pull request by stephane-segning**
I added an automatic script to test the code and lint it to see bad or wrong code

### CODE REVIEW

**Comment by Koufan-De-King** [comment]
Everything is all right, @stephane-segning
You may proceed with the merging.

**Comment by stephane-segning** [comment]
@Koufan-De-King you closed it.

**Review by Koufan-De-King — APPROVED** [review]
All good now.

My bad- really sorry for the previous error, sir.

**Review by AssahBismarkabah — APPROVED** [review]
hello @stephane-segning run successfully sir

**Review by nancymuyeh — COMMENTED** [review]
Good work sir @stephane-segning .It runs successfully

**Comment by AssahBismarkabah** [comment]
hello sir @stephane-segning merged ticket #39 since it has being approved  already

**Pull request merged**
