### PR TITLE
chore(github): created an action to test the code automatically

### LINKED ISSUE #9: Ticket N°-1::2: Setup automatic tests

### PR DESCRIPTION
**Pull request by stephane-segning**
I added a code for GitHub workflow to automatically test the code on each PR.

### CODE REVIEW

**Comment by stephane-segning** [comment]
I need the previous PR to complete first #15

**Comment by AssahBismarkabah** [comment]
hello sir @stephane-segning, did not add action to check for the branch and commit convention in the `pr.yaml`

**Review by ArmandMeppa — APPROVED** [review]

**Comment by stephane-segning** [comment]
> hello sir @stephane-segning, did not add action to check for the branch and commit convention in the `pr.yaml`

I'm working on it now @AssahBismarkabah

**Review by AssahBismarkabah — CHANGES_REQUESTED** [review]
ok sir

**Review by Awambeng — CHANGES_REQUESTED** [review]
I verified but there is a small issue

image

**Comment by stephane-segning** [comment]
> I verified but there is a small issue
> 
> image

This is normal @Awambeng, because the test name is not good. I fixed it already and I'll push next.

**Comment by Awambeng** [comment]
> > I verified but there is a small issue
> > image
> 
> This is normal @Awambeng, because the test name is not good. I fixed it already and I'll push next.

Ok prof

**Review by Awambeng — APPROVED** [review]
Good job

**Review by AssahBismarkabah — APPROVED** [review]

**Comment by AssahBismarkabah** [comment]
merged this PR for ticket #16

**Pull request merged**
